replicaCount: 1
image:
  repository: empathyco/cost-report
  pullPolicy: IfNotPresent
  tag: "sha-27ab0c2"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: 
  runAsUser: 10100
  allowPrivilegeEscalation: false
service:
  type: ClusterIP
  port: 8080
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus
  dashboards:
    enabled: true
