name: reviewdog
on: ["pull_request"]
jobs:
  reviewdog:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        go: ["1.17.x"]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: ${{ matrix.go }}
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: golangci-lint-check
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: "--tests=false --exclude-use-default=false --enable-all  -D gci -D scopelint -D exhaustivestruct  -D wsl -D gomnd -D gochecknoglobals -D lll -D golint -D forbidigo -D ireturn"
          level: "warning"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
      - name: golangci-lint-pr-preview
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: "--tests=false --exclude-use-default=false --enable-all  -D gci -D scopelint -D exhaustivestruct  -D wsl -D gomnd -D gochecknoglobals -D lll -D golint -D forbidigo -D ireturn"
          level: "warning"          
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
