name: "CI"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Run CI"
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        go: ["1.16.x", "1.17.x"]
    steps:
    - uses: actions/checkout@v1
      with:
       fetch-depth: 1
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: ${{ matrix.go }}
    - run: "CI=CI go test ./..."
    - run: "go vet ./..."
    - uses: dominikh/staticcheck-action@v1.1.0
      with:
        version: "2021.1.1"
        install-go: false
        cache-key: ${{ matrix.go }}